FROM dl-playground/final
LABEL maintainer="Sean Sall <ssall@alumni.nd.edu>"

arg user

USER $user

RUN git clone https://github.com/sallamander/.dotfiles.git && \
    cd $HOME/.dotfiles && \
    bash install.sh
