dataset:
    fpath_df_train: /data/imagenet/from_access_links/metadata_lists/df_classification_train_set.csv
    fpath_df_validation: /data/imagenet/from_access_links/metadata_lists/df_classification_validation_set.csv
    importpath: datasets.imagenet_dataset.ImageNetDataSet
    init_params: 
        config:
            height: 227
            width: 227
    train_transformations:
        - datasets.ops.per_image_standardization:
            sample_keys:
                value:
                    - 'image'
        - torchvision.transforms.functional.to_tensor:
            sample_keys:
                value: 
                    - 'image'
        - torch.tensor:
            sample_keys:
                value: 
                    - 'label'
            dtype:
                import: true
                value: 'torch.long'
    validation_transformations:
        - datasets.ops.per_image_standardization:
            sample_keys:
                value:
                    - 'image'
        - torchvision.transforms.functional.to_tensor:
            sample_keys:
                value: 
                    - 'image'
        - torch.tensor:
            sample_keys:
                value: 
                    - 'label'
            dtype:
                import: true
                value: 'torch.long'
    train_loading_params:
        batch_size: 128
        shuffle: True
        num_workers: 4
    validation_loading_params:
        batch_size: 128
        shuffle: False
        num_workers: 2
network:
    importpath: networks.pytorch.object_classification.alexnet.AlexNet
    init_params:
        config:
            n_channels: 3
            n_classes: 1000
trainer:
    importpath: training.pytorch.imagenet_trainer.ImageNetTrainer
    init_params:
        config:
            optimizer: 'Adam'
            loss: 'CrossEntropyLoss'
            batch_size: 128
            n_epochs: 10
